version: "3.9"
services:
  tpagiles-image:
    container_name: tpagiles-container
    build:
      context: .
      dockerfile: Dockerfile
    image: tpagiles-image
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
networks:
  spring-network:
volumes:
  mysql-volume: