version: '3.8'
services:
  backend:
    build:
      context: ../../..          # sube tres niveles hasta donde está pom.xml
      dockerfile: src/main/java/com/tpagiles/app_licencia/infra/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge